doyourownswing/doyourownswing.github.io

web/public/index.html, web/src/index.css
Mostly copied straight from google's api
https://fonts.google.com/selection/embed
=> Sets default font to Nunito

web/src/components/home/Home.js, web/src/components/home/messages.js, web/src/components/home/subcomponents/song_of_the_week/song_of_the_week.js, web/src/components/home/subcomponents/upcoming_events/upcoming_events.js, web/src/components/home/subcomponents/welcome/Welcome.js, web/src/components/home/subcomponents/what_is_wcs/what_is_wcs.js, web/src/components/home/subcomponents/who_we_are/who_we_are.js
Sets up the directory for home page structure and creates some skeleton components.
This was we can work on each section in parallel
=> Home page skeleton

web/src/components/about/about.js, web/src/components/contact/contact.js, web/src/components/health/health.js, web/src/components/home/home.js, web/src/components/home/subcomponents/welcome/welcome.js, web/src/components/schedule/schedule.js
git is wonky as shit. had to set `ignorecase = false` in .git/config
This hopefully just renames the files. And deletes an extra one that i renamed but my computer didnt get rid of
=> Fix slippery renaming issue

web/src/data/events.js
Need to update the UI to gracefully handle no events, but for now, just add more events
=> Adds a few more events

web/src/data/events.js
It's not coding, it's editing data.
=>  Adds FB link and title to upcoming events

web/src/common/theme.js, web/src/components/home/subcomponents/song_of_the_week/quote_attribution.js, web/src/components/home/subcomponents/song_of_the_week/quote_attribution.styles.js, web/src/components/home/subcomponents/song_of_the_week/song_card.styles.js, web/src/data/songs_of_the_week.js
Also updates song card styling for exactly 602 pixel width screens
=> Adds a new song of the week

web/src/common/theme.js, web/src/components/home/subcomponents/welcome/welcome.js, web/src/components/home/subcomponents/welcome/welcome.styles.js, web/src/components/start_here/start_here.js, web/src/components/start_here/start_here.styles.js, web/src/index.js, web/src/infra/feature_flags.js
Adds the new files with nothing one it
=> Creates start here page and adds it to the router if the flag is on

web/src/components/home/subcomponents/what_is_wcs/messages.js, web/src/components/home/subcomponents/what_is_wcs/video_renderer/default_video_renderer.js, web/src/components/home/subcomponents/what_is_wcs/video_renderer/default_video_renderer.styles.js, web/src/components/home/subcomponents/what_is_wcs/what_is_wcs.js, web/src/components/home/subcomponents/what_is_wcs/what_is_wcs.styles.js
New card for What is West Coast Swing
Couple of issues I need help with:
* The width of the card is weird, and I had to set a very specific max-width to match the Upcoming Events section. Would like to make this cleaner
* Couldn't figure out bullet points with Typography tags
* double check video width is nice for all sizes
=> Create What is WCS section

web/src/components/footer/subcomponents/brand/brand.styles.js, web/src/components/home/subcomponents/upcoming_events/event_cards/dyos_event_card.styles.js, web/src/components/home/subcomponents/upcoming_events/event_cards/event_card.js
=> Uses date util and gives more breathing room to schedule

web/src/components/home/subcomponents/upcoming_events/messages.js, web/src/components/home/subcomponents/upcoming_events/upcoming_events.js, web/src/components/home/subcomponents/upcoming_events/upcoming_events.styles.js, web/src/data/events.js
1. Adds more events
2. Adds a placeholder if no events are found
3. Don't show the second event if there isn't one
=> Make upcoming events resilient

web/jsconfig.json, web/src/common/constants.js, web/src/common/theme.js, web/src/components/footer/footer.styles.js, web/src/components/start_here/messages.js, web/src/components/start_here/start_here.js, web/src/components/start_here/start_here.styles.js, web/src/components/start_here/subcomponents/before_the_event.js, web/src/components/start_here/subcomponents/faqs.js, web/src/components/start_here/subcomponents/when_you_arrive.js, web/src/index.js
Looks like this kinda:
https://docs.google.com/drawings/d/17ZKYrQq0rGaVpm65iewW6ItTRPr3tE6xX7-qqAodY7Q/edit
Just puts a bunch of text on a page, nothing fancy
=> Start here page

web/src/data/events.js
Adds events through the end of August - only July 18 has a FB event link
Adds the new class names for level 1, 2, 3
=> Create more events

web/src/common/messages.js, web/src/data/events.js
=> fixed this week to be mini dyos

web/src/components/start_here/messages.js, web/src/components/start_here/subcomponents/before_the_event.js, web/src/infra/feature_flags.js
updates class names and descriptions. copy pasta for facebook events.
ALSO ENABLES IT CUZ WHY NOT
=> Updates the classes part of the start here guide

web/src/components/start_here/messages.js, web/src/data/events.js, web/src/data/songs_of_the_week.js
- Fixed Mini DYOS schedule times
- Added events through the end of October, assuming all are standard DYOS events. Will need to double check on the Boogie by the Bay weekend
- Fix typo on Start Here page
=> Misc fixes

web/src/common/nav_options.js
=> if conditions were borked and backwards

web/src/common/nav_options.js, web/src/common/pages.js, web/src/components/nav_bar/nav_bar.js, web/src/index.js, web/src/page_registry.js
Who left that giant thing of if statements in the index file? definitely not scalable. When I tried to rename the thing and the url, it broke cuz i had to rename it in several places. So what did I do? I refactored that baby. There's now two more files and a whole lot more overhead to make sure I only have to rename stuff in one place.
=> Rename schedule to classes

web/src/components/home/subcomponents/who_we_are/messages.js, web/src/components/home/subcomponents/who_we_are/who_we_are.js
Just looked at the bit.ly/dyosinfo and saw that there were some updates. Makenzie also said what I wrote was gross (took her long enough)
#45 #38
=> Updates mission statements and values

web/src/common/constants.js, web/src/common/theme.js, web/src/components/common/link.js, web/src/components/common/link.styles.js, web/src/components/home/subcomponents/song_of_the_week/messages.js, web/src/components/home/subcomponents/song_of_the_week/quote.js, web/src/components/home/subcomponents/song_of_the_week/quote.styles.js, web/src/components/home/subcomponents/song_of_the_week/song_of_the_week.js, web/src/components/home/subcomponents/song_of_the_week/song_of_the_week.styles.js, web/src/data/songs_of_the_week.js
1. Adds some more songs to the songs of the week (thanks Jen)
2. Now we don't have to come up with these lame ass quotes if we don't want to
3. Created a spotify playlist with all the songs that have been featured in the past
4. And created a whole ass Link component cuz the one that comes out of the box with Material UI is poo poo on a stick.
5. Also makes some styling better cuz turns out gap is pretty cool and nicer than padding bottom
Nice little link to the playlist if there is a quote
Nice default messaging if there is no quote and links to the playlist
=> More songs, no quote, styled link, dyos playlist? oh boy

web/src/components/home/subcomponents/welcome/messages.js, web/src/components/home/subcomponents/welcome/welcome.js, web/src/components/home/subcomponents/welcome/welcome.styles.js
* Added messages
* centered on small screens
* gave more breathing room
* made title bigger on small screens to stay interesting
* added non-breaking spaces to welcome descriptions
Medium screen 
Small screen (600-900px wide)
XS screen (<600px)
=> Welcome section updates

web/src/common/event_types.js, web/src/common/theme.js, web/src/components/home/subcomponents/upcoming_events/event_cards/boogie_event_card.js, web/src/components/home/subcomponents/upcoming_events/event_cards/event_card.styles.js, web/src/components/home/subcomponents/upcoming_events/event_renderer.js, web/src/components/home/subcomponents/upcoming_events/upcoming_events.js, web/src/data/events.js
Refactors event type so that we can access the value in the component renderer.
Introduces a new type for boogie. May refactor this to be a general ConventionWithoutClass type.
Added one for NoClass but haven't done anything with it yet. May remove later.
Already deployed changes cuz we're behind schedule. 
Added some TODOs for refactoring the event object cuz it scales poorly at the moment
=> Updates events for the rest of the year

web/src/data/songs_of_the_week.js
Adds some more songs based on what we're doing in class.
Already deployed.
=> Adds songs we're doing in class to the song of the week list

web/src/data/events.js
=> Adds new events

web/src/common/theme.js, web/src/components/home/subcomponents/upcoming_events/event_cards/teacher_training_event_card.js, web/src/components/nav_bar/announcement.js, web/src/components/nav_bar/announcement.styles.js, web/src/components/nav_bar/nav_bar.js, web/src/data/announcements.js, web/src/data/events.js, web/src/data/songs_of_the_week.js, web/src/index.js, web/src/utils/date_utils.js
Honestly, very hacky. But best i could do at midnight.
Follows similar structure of adding configurable announcements settable based on dates.
Also tries to make things a bit better
=> Add our very first announcement

web/src/components/home/subcomponents/hero/messages.js, web/src/data/announcements.js, web/src/data/events.js
Shuffles hero adjectives, ends the winter break announcement early, and adds events for the rest of the month
=> Some smol changes

web/src/data/events.js
=> New level one time and descriptions 

web/src/common/theme.js, web/src/components/home/subcomponents/upcoming_events/event_cards/event_card.js, web/src/components/home/subcomponents/upcoming_events/event_cards/event_card.styles.js, web/src/components/nav_bar/nav_bar.js, web/src/components/nav_bar/nav_bar.styles.js
Mainly changes the event card button. The nav bar options look a bit better, but they're not even visible yet
=> Makes buttons and header items more consistent

web/src/components/home/subcomponents/upcoming_events/event_cards/event_card.js, web/src/components/start_here/messages.js
* Added L4 description
* Updated times to be accurate
* Slightly reworked the descriptions for each level now that there's more of them
=> Updated start here page with new class times (L1-L4)

web/src/common/theme.js, web/src/components/home/subcomponents/who_we_are/who_we_are.js, web/src/components/home/subcomponents/who_we_are/who_we_are.styles.js, web/src/components/schedule/schedule.js, web/src/components/schedule/subcomponents/classes/classes.js, web/src/components/schedule/subcomponents/classes/classes.styles.js, web/src/components/schedule/subcomponents/classes/messages.js, web/src/infra/feature_flags.js
Creates a new component that displays the classes as responsive cards with details.
Updates the feature flag.
Also adds some values to the base palette and removes custom gray colors hexcodes.
TODOs are to include some text saying you can come to multiple classes and email if you have questions, and maybe a picture. The rest of the content will come in followup PRs
=> Adds Classes cards to the Classes page

web/src/data/events.js
Adds the new deets for the next 2 events, adds mini dyos, and tentatively adds the next default events through july
=> More events

web/src/data/events.js
Really wish our classes page was done so that we could do more fun stuff with the upcoming events section
=> Updates the names of this months events

web/src/components/schedule/subcomponents/payment/payment.js
1. Open links in new tabs
2. Update links to be mobile and web friendly, and not the same as the qr code link
=> fixes buttons in payments section

web/src/components/nav_bar/nav_bar.styles.js, web/src/infra/feature_flags.js
about time amirite?
Makes the classes page properly public via the website. Since it's the only other page, clean up the styling for the nav bar. Also updates some of the css since we've learned what's better.
=> Launches the classes page - and makes some ux cleanup
